# @host = http://localhost:5000
@host = https://w3search.thenextblock.com

GET {{host}}/

###
# @name query
POST {{host}}/api/v1/
content-type: application/json

{
    "question": "Find posts about “Order Flow Auction”  and extract most active Authors and list them: Author | Message Count | Summarise Context",
    "collection": "discord",
    "filters": ["flashbots", "thegraph"],
    "maxdocs": "50"
}

###

# @name query1
POST {{host}}/api/v1/
content-type: application/json

{
    "question": "Why did Solidity deprecate the 'years' keyword?",
    "collection": "discord",
    "filters": ["flashbots"],
    "maxdocs": "400"
}


###
# @name query2
POST {{host}}/api/v1/
content-type: application/json

{
    "question": "can you list the bets resourses about Proposer and Builder separation?",
    "collection": "discord",
    "filters": ["arbitrum", "flashbots", "thegraph"],
    "maxdocs": "500"
}


###
# @name Vector Search
POST {{host}}/api/v1/search/
content-type: application/json

{
    "question": "can you list the bets resourses about Proposer and Builder separation?",
    "collection": "discord",
    "filters": [],
    "maxdocs": "500",
    "model": "gpt-4"
}
