@host = http://localhost:5000


GET {{host}}/

###
# @name query
POST {{host}}/api/v1/
content-type: application/json

{   
    "question": "can you list the bets resourses about Proposer and Builder separation?",
    "collection": "discord",
    "filters": [],
    "maxdocs": "400",
    "model": "gpt-4"
}

###

# @name query1
POST {{host}}/api/v1/
content-type: application/json

{
    "question": "Why did Solidity deprecate the 'years' keyword?",
    "collection": "discord",
    "filters": ["flashbots"],
    "maxdocs": "400"
}



###
# @name Vector Search
POST {{host}}/api/v1/search/
content-type: application/json

{
    "question": "What is StakeSquid ?",
    "collection": "discord",
    "filters": [],
    "maxdocs": "400",
    "model": "gpt-4"
}
